default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "ThreeToDo.xcworkspace", scheme: "ThreeToDo")
    upload_to_testflight
  end
end
